eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8762/eureka
  server:
    #关闭心跳监测功能
    enable-self-preservation: true
server:
  port: 8761

spring:
  application:
    name: eureka-server